#!/bin/bash

#Script for  defining an array

myARRAY=( 1 2 3 4 5 ) # this how to define an array


echo "${myArray[*]}" #This is how to print the entiver value of an array

echo "${myARRAY[3]}" #This is how to print an value of array having index 3

echo "${myARRAY[*]:2}" #This is how to print an value of array from index2 

echo "lenght of an array ${#myARRAY[@]}" #This is how to print lenght of an array

# this is how you can write multiple comments

<<comment

this is the script

to test the array

definition

comment

## this is to test mere conflict
